let a = 1;
let a1 = 0;
let a2 = -3;


console.log("Task №1");
console.log();

if(a == 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a1 == 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a2 == 0){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();


console.log("Task №2");
console.log();

if(a > 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a1 > 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a2 > 0){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();


console.log("Task №3");
console.log();

if(a < 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a1 < 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a2 < 0){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();



console.log("Task №4");
console.log();

if(a >= 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a1 >= 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a2 >= 0){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();



console.log("Task №5");
console.log();

if(a <= 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a1 <= 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a2 <= 0){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();




console.log("Task №6");
console.log();

if(a != 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a1 != 0){
    console.log("True");
}
else{
    console.log("False");
}

if(a2 != 0){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();




console.log("Task №7");
console.log();

let b = "test";
let b1 = "тест";
let b2 = "3";

if(b == "test"){
    console.log("True");
}
else{
    console.log("False");
}

if(b1 == "test"){
    console.log("True");
}
else{
    console.log("False");
}

if(b2 == "test"){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();



console.log("Task №8");
console.log();



let с = "1";
let с1 = 1;
let с2 = 3;

if(с == "1" & typeof "1" == typeof "1"){
    console.log("True");
}
else{
    console.log("False");
}

if(с1 == "1" & typeof 1 == typeof "1"){
    console.log("True");
}
else{
    console.log("False");
}

if(с2 == "1" & typeof 3 == typeof "1"){
    console.log("True");
}
else{
    console.log("False");
}
console.log();
console.log();



console.log("Task №9");
console.log("Option 1");

let test = true;
let test2 = false;


if(test == true){
    console.log("True");
}
else{
    console.log("False");
}

if(test2 == true){
    console.log("True");
}
else{
    console.log("False");
}

console.log();
console.log("Option 2");
console.log();


for(let i = 1; i <= 2; i++){
    if(test == true){
        console.log("True");
    }
    else{
        console.log("False");
    }
    test = false;
}


console.log();
console.log();



console.log("Task №10");
console.log("Option 1");

test = true;



if(test != true){
    console.log("True");
}
else{
    console.log("False");
}

if(test2 != true){
    console.log("True");
}
else{
    console.log("False");
}

console.log();
console.log("Option 2");
console.log();


for(let i = 1; i <= 2; i++){
    if(test != true){
        console.log("True");
    }
    else{
        console.log("False");
    }
    test = false;
}


console.log();
console.log();



console.log("Task №11");
console.log();

a = 5;
if(a > 0 & a < 5){
    console.log("True");
}
else{
    console.log("False");
}

a = 0;
if(a > 0 & a < 5){
    console.log("True");
}
else{
    console.log("False");
}

a = -3;
if(a > 0 & a < 5){
    console.log("True");
}
else{
    console.log("False");
}

a = 2;
if(a > 0 & a < 5){
    console.log("True");
}
else{
    console.log("False");
}


console.log();
console.log();



console.log("Task №12");
console.log();

a = 5;
if(a == 0 || a == 2){
    console.log(a + 7);
}
else{
    console.log(a / 10);
}

a = 0;
if(a == 0 || a == 2){
    console.log(a + 7);
}
else{
    console.log(a / 10);
}

a = -3;
if(a == 0 || a == 2){
    console.log(a + 7);
}
else{
    console.log(a / 10);
}

a = 2;
if(a == 0 || a == 2){
    console.log(a + 7);
}
else{
    console.log(a / 10);
}

console.log();
console.log();



console.log("Task №13");
console.log();

a = 1;
b = 3;
if(a <= 1 & b >= 3){
    console.log(a + b);
}
else{
    console.log(a - b);
}

a = 0;
b = 6;
if(a <= 1 & b >= 3){
    console.log(a + b);
}
else{
    console.log(a - b);
}

a = 3;
b = 5;
if(a <= 1 & b >= 3){
    console.log(a + b);
}
else{
    console.log(a - b);
}


console.log("Task №14");
console.log();

a = 3;
b = 5;
if(a > 2 & a < 11 || b >= 6 & b < 14){
    console.log("True");
}
else{
    console.log("False");
}

console.log();

a = 1;
b = 15;
if(a > 2 & a < 11 || b >= 6 & b < 14){
    console.log("True");
}
else{
    console.log("False");
}

console.log("Task №15");
console.log();

let result;

for(let num = 1; num <= 5; num++){
    switch(num){
        case 1:
            result = "Winter";
            break;
                            
        case 2:
            result = "Spring";
            break;
        
        case 3:
            result = "Summer";
            break;

        case 4:
            result = "Autumn";
            break;
        
        default:
            result = "Some time of the year";
    }
    console.log(result);
    console.log();
}
